Re-add uninstalling Homebrew + running bash script

diff --git a/.github/workflows/run-bash-script-on-mac-os.yml b/.github/workflows/run-bash-script-on-mac-os.yml
--- a/.github/workflows/run-bash-script-on-mac-os.yml
+++ b/.github/workflows/run-bash-script-on-mac-os.yml
@@ -4,6 +4,47 @@ jobs:
   Run-Script:
     runs-on: macos-12
     steps:
+        # Homebrew is pre-installed on the GitHub Actions MacOS Runner (Virtual Machine) - see: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#:~:text=Composer%202.5.5-,Homebrew%204.0.15,-Miniconda%2023.3.1
+        # - So we need to remove it
+        # Uninstalling Homebrew using the following command recommended in the docs doesn't fail, but doesn't remove everything it should do due to not having sudo permissions:
+        # NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
+        # - So we need to use sudo to run it
+      - name: Uninstall pre-installed Homebrew version
+        run: |
+          curl -sLO https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh
+          chmod +x ./uninstall.sh
+          sudo ./uninstall.sh --force
+      - name: Remove remaining pre-installed Homebrew directories that weren't removed
+        # The Homebrew output tells us that these files possibly related to Homebrew on the GitHub Actions MacOS Runner haven't been deleted, so we should remove them:
+        run: |
+          sudo rm -rf /usr/local/.com.apple.installer.keep
+          sudo rm -rf /usr/local/Frameworks/
+          sudo rm -rf /usr/local/Homebrew/
+          sudo rm -rf /usr/local/aws-cli/
+          sudo rm -rf /usr/local/bin/
+          sudo rm -rf /usr/local/etc/
+          sudo rm -rf /usr/local/include/
+          sudo rm -rf /usr/local/lib/
+          sudo rm -rf /usr/local/microsoft/
+          sudo rm -rf /usr/local/miniconda/
+          sudo rm -rf /usr/local/opt/
+          sudo rm -rf /usr/local/sbin/
+          sudo rm -rf /usr/local/sessionmanagerplugin/
+          sudo rm -rf /usr/local/share/
+          sudo rm -rf /usr/local/var/
+      - name: Ensure reportedly deleted pre-installed Homebrew directories no longer exist
+        # The Homebrew output tells us that these should have been deleted, but we should make sure that they are definitely removed:
+        run: |
+          sudo rm -rf /usr/local/Caskroom
+          sudo rm -rf /usr/local/bin/brew
+      - name: Ensure pre-installed Homebrew version has been removed
+        # Check if Homebrew is installed using `command -v brew`. If Homebrew is not already installed, this command will not print anything to standard error or standard output.
+        # If Homebrew is already installed (if anything is printed to standard error or standard output), print a message stating that the GitHub Workflow needs to be changed to ensure that Homebrew is not already installed on the macOS virtual machine, and fail the GitHub Workflow.
+        run: |
+          if command -v brew &> /dev/null
+            then echo 'Homebrew is still installed but it should have been removed. Uninstall Homebrew to ensure that the bash script does not try to install Homebrew for a second time.'
+            exit 1
+          fi
       - name: Remove Xcode
         run: sudo rm -rf /Applications/Xcode_14.2.app/
       - name: Delete Xcode in '/' directory
@@ -19,6 +60,9 @@ jobs:
             echo "Xcode is installed but it should have been removed. Uninstall Xcode to ensure that the bash script does not try to install Xcode for a second time."
             exit 1
           fi
+      - uses: actions/checkout@v3
+      - name: Run bash script
+        run: ./set-up-laptop.sh
 
       # - name: See if Xcode Command Line Tools is installed where expected
       #   run: ls -la /Library/Developer/CommandLineTools
@@ -32,47 +76,6 @@ jobs:
 
       # Might have to do this as well - see if you need it: You also need to reset the default command-line tools by entering this command "sudo xcode-select -r"
 
-      #   # Homebrew is pre-installed on the GitHub Actions MacOS Runner (Virtual Machine) - see: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#:~:text=Composer%202.5.5-,Homebrew%204.0.15,-Miniconda%2023.3.1
-      #   # - So we need to remove it
-      #   # Uninstalling Homebrew using the following command recommended in the docs doesn't fail, but doesn't remove everything it should do due to not having sudo permissions:
-      #   # NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
-      #   # - So we need to use sudo to run it
-      # - name: Uninstall pre-installed Homebrew version
-      #   run: |
-      #     curl -sLO https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh
-      #     chmod +x ./uninstall.sh
-      #     sudo ./uninstall.sh --force
-      # - name: Remove remaining pre-installed Homebrew directories that weren't removed
-      #   # The Homebrew output tells us that these files possibly related to Homebrew on the GitHub Actions MacOS Runner haven't been deleted, so we should remove them:
-      #   run: |
-      #     sudo rm -rf /usr/local/.com.apple.installer.keep
-      #     sudo rm -rf /usr/local/Frameworks/
-      #     sudo rm -rf /usr/local/Homebrew/
-      #     sudo rm -rf /usr/local/aws-cli/
-      #     sudo rm -rf /usr/local/bin/
-      #     sudo rm -rf /usr/local/etc/
-      #     sudo rm -rf /usr/local/include/
-      #     sudo rm -rf /usr/local/lib/
-      #     sudo rm -rf /usr/local/microsoft/
-      #     sudo rm -rf /usr/local/miniconda/
-      #     sudo rm -rf /usr/local/opt/
-      #     sudo rm -rf /usr/local/sbin/
-      #     sudo rm -rf /usr/local/sessionmanagerplugin/
-      #     sudo rm -rf /usr/local/share/
-      #     sudo rm -rf /usr/local/var/
-      # - name: Ensure reportedly deleted pre-installed Homebrew directories no longer exist
-      #   # The Homebrew output tells us that these should have been deleted, but we should make sure that they are definitely removed:
-      #   run: |
-      #     sudo rm -rf /usr/local/Caskroom
-      #     sudo rm -rf /usr/local/bin/brew
-      # - name: Ensure pre-installed Homebrew version has been removed
-      #   # Check if Homebrew is installed using `command -v brew`. If Homebrew is not already installed, this command will not print anything to standard error or standard output.
-      #   # If Homebrew is already installed (if anything is printed to standard error or standard output), print a message stating that the GitHub Workflow needs to be changed to ensure that Homebrew is not already installed on the macOS virtual machine, and fail the GitHub Workflow.
-      #   run: |
-      #     if command -v brew &> /dev/null
-      #       then echo 'Homebrew is still installed but it should have been removed. Uninstall Homebrew to ensure that the bash script does not try to install Homebrew for a second time.'
-      #       exit 1
-      #     fi
       # # # They do exist - it prints out: /Applications/Xcode_14.2.app/Contents/Developer
       # # - name: Check if Xcode Command Line Tools are installed
       # #   run: xcode-select -p
@@ -102,6 +105,3 @@ jobs:
       #   run: sudo xcode-select -r
       # - name: Re-check if Xcode Command Line Tools are installed
       #   run: xcode-select -p
-      # - uses: actions/checkout@v3
-      # - name: Run bash script
-      #   run: ./set-up-laptop.sh
